server:
  port: 8084


spring:
  zipkin:
    base-url:http://localhost:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/CitizenDB
    password: root@R12
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: CITIZEN-SERVICE