server:
  port: 8083
logging:
  file: /home/neosoft/Desktop/micro.log
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: CITIZEN-SERVICE
          uri:
            lb://CITIZEN-SERVICE
          predicates:
            - Path=/citizen/**
          filters:
            - AuthenticationFilter

        - id: VACCINATION-CENTER-SERVICE
          uri:
            lb://VACCINATION-CENTER-SERVICE
          predicates:
            - Path=/vaccinationcenter/**
          filters:
            - AuthenticationFilter

        - id: IDENTITY-SERVICE
          uri:
            lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**


